name: Download and Patch APK

on:
  workflow_dispatch: # 手动触发

jobs:
  download_and_patch:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 使用 SSH 登录你的服务器并 wget 下载 XAPK
      - name: Download XAPK on Remote Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /tmp
            wget -O com.oddno.lovelive.xapk \
              --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
              --referer="https://apkpure.com" \
              "https://d.apkpure.com/b/XAPK/com.oddno.lovelive?version=latest"

      # 3. 将 XAPK 下载回 GitHub Actions runner
      - name: Copy XAPK from Server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: /tmp/com.oddno.lovelive.xapk
          target: ./app.xapk

      # 4. 解压 XAPK
      - name: Extract XAPK
        run: unzip -o app.xapk -d app

      # 5. 执行 APKEditor 和 LSPatch
      - name: Patch APK
        run: |
          java -jar APKEditor.jar m -i app/
          java -jar lspatch.jar app_merged.apk -m linkura-localify-v1.0.1-debug-arm64-v8a.apk -o result/

      # 6. 发布到 GitHub Release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: result/*
          token: ${{ secrets.GITHUB_TOKEN }}
