name: XAPK Patch Release

on:
  workflow_dispatch:
    inputs:
      linkura_version:
        description: 'Linkura version (API trigger)'
        required: false
        default: '手动'
      linkura_localify_version:
        description: 'Linkura-localify version (API trigger)'
        required: false
        default: '手动'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client jq unzip wget

      - name: Write SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Remote wget XAPK to server
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<'EOF'
            set -eux
            mkdir -p /opt/linkura-localify-auto-release-web/data
            cd /opt/linkura-localify-auto-release-web/data
            wget -O latest.apk \
              --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
              "https://d.apkpure.com/b/XAPK/com.oddno.lovelive?version=latest"
          EOF

      - name: Copy XAPK from server
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa -P ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/linkura-localify-auto-release-web/data/latest.apk \
            ./app.xapk

      - name: Download linkura-localify apk
        run: |
          url=$(curl -s https://api.github.com/repos/ChocoLZS/linkura-localify/releases/latest \
            | jq -r '.assets[] | select(.name | test("linkura-localify-.*-debug-arm64-v8a\\.apk")) | .browser_download_url' \
            | head -n1)
          wget -O linkura-localify.apk "$url"

      - name: Expand XAPK
        run: unzip -o app.xapk -d app

      - name: Run APKEditor
        run: java -jar APKEditor.jar m -i app/

      - name: Run LSPatch
        run: |
          merged_apk=$(find . -maxdepth 1 -name "*_merged.apk" | head -n1)
          if [ -z "$merged_apk" ]; then
            echo "❌ 未找到 _merged.apk，检查 APKEditor 输出"
            exit 1
          fi
          java -jar lspatch.jar "$merged_apk" -m linkura-localify.apk -o result
          ls -lh result

      - name: Upload Release (both merged & patched)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.linkura_version }}
          name: Linkura Patch Release ${{ github.event.inputs.linkura_version }}
          body: |
            Linkura version: ${{ github.event.inputs.linkura_version }}
            Linkura-localify version: ${{ github.event.inputs.linkura_localify_version }}
            Release time: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            $(find . -maxdepth 1 -name "*_merged.apk")
            $(find result -maxdepth 1 -name "*.apk")
