name: XAPK Patch Release

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-patch:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Create folders
        run: |
          mkdir app
          mkdir result
        shell: powershell

      - name: Download app.xapk from APKPure
        run: |
          Write-Host "Downloading app.xapk..."
          $url = "https://d.apkpure.com/b/XAPK/com.oddno.lovelive?version=latest"
          $output = "app.xapk"
          Invoke-WebRequest -Uri $url -OutFile $output -Headers @{
            "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
          }
        shell: powershell

      - name: Download latest linkura-localify arm64-v8a APK
        run: |
          Write-Host "Fetching latest release from GitHub..."
          $apiUrl = "https://api.github.com/repos/ChocoLZS/linkura-localify/releases/latest"
          $release = Invoke-RestMethod -Uri $apiUrl
          $asset = $release.assets | Where-Object { $_.name -match "linkura-localify-.*-debug-arm64-v8a\.apk" } | Select-Object -First 1
          Write-Host "Downloading $($asset.name)..."
          Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $asset.name
        shell: powershell

      - name: Expand XAPK
        run: Expand-Archive -Path .\app.xapk -DestinationPath .\app -Force
        shell: powershell

      - name: Run APKEditor
        run: java -jar .\APKEditor.jar m -i .\app\
        shell: powershell

      - name: Run LSPatch
        run: |
          $appMerged = Get-ChildItem -Path .\app -Filter "*_merged.apk" | Select-Object -First 1
          Write-Host "Found merged APK: $($appMerged.FullName)"
          $patchApk = Get-ChildItem -Filter "linkura-localify-*-debug-arm64-v8a.apk" | Select-Object -First 1
          java -jar .\lspatch.jar $appMerged.FullName -m $patchApk.FullName -o .\result\
        shell: powershell

      - name: Upload result to release
        uses: ncipollo/release-action@v1
        with:
          tag: "patch-result-${{ github.run_number }}"
          name: "Patch Result ${{ github.run_number }}"
          files: result/*
          overwrite: true
