name: XAPK Patch Release

on:
  workflow_dispatch:
    inputs:
      linkura_version:
        description: 'Linkura version (required)'
        required: true
        default: '手动'
      linkura_localify_version:
        description: 'Linkura-localify version (optional)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client jq unzip wget

      - name: Write SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Remote wget XAPK to server
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<'EOF'
            set -eux
            mkdir -p /opt/linkura-localify-auto-release-web/data
            cd /opt/linkura-localify-auto-release-web/data
            wget -O latest.apk \
              --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
              "https://d.apkpure.com/b/XAPK/com.oddno.lovelive?version=latest"
            ls -lh latest.apk
          EOF

      - name: Copy XAPK from server
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa -P ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/linkura-localify-auto-release-web/data/latest.apk \
            ./app.xapk
          ls -lh app.xapk

      - name: Download linkura-localify apk
        run: |
          url=$(curl -s https://api.github.com/repos/ChocoLZS/linkura-localify/releases/latest \
            | jq -r '.assets[] | select(.name | test("linkura-localify-.*-debug-arm64-v8a\\.apk")) | .browser_download_url' \
            | head -n1)
          wget -O linkura-localify.apk "$url"
          ls -lh linkura-localify.apk

      - name: Expand XAPK
        run: unzip -o app.xapk -d app

      - name: Run APKEditor (merge)
        run: java -jar APKEditor.jar m -i app/

      - name: Find merged APK
        run: |
          MERGED_APK=$(find . -maxdepth 1 -name "*_merged.apk" | head -n1)
          if [ -z "$MERGED_APK" ]; then
            echo "❌ 未找到 _merged.apk"
            exit 1
          fi
          echo "MERGED_APK=$MERGED_APK" >> $GITHUB_ENV
          cp "$MERGED_APK" result/merged.apk

      - name: Run LSPatch
        run: |
          java -jar lspatch.jar "$MERGED_APK" -m linkura-localify.apk -o result
          PATCHED_APK=$(find result -type f -name '*.apk' | head -n1)
          echo "PATCHED_APK=$PATCHED_APK" >> $GITHUB_ENV

      - name: Prepare release info
        run: |
          LINKURA_VERSION="${{ github.event.inputs.linkura_version }}"
          LINKURA_LOCALIFY_VERSION="${{ github.event.inputs.linkura_localify_version }}"
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          RELEASE_BODY="Linkura version: ${LINKURA_VERSION}\nLinkura-localify version: ${LINKURA_LOCALIFY_VERSION}\nBuild date: ${DATE}"
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo -e "$RELEASE_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "RELEASE_TITLE=${LINKURA_VERSION}" >> $GITHUB_ENV

      - name: Upload merged APK release
        uses: ncipollo/release-action@v1
        with:
          tag: merged-${{ github.run_number }}
          name: Merged APK - ${{ env.RELEASE_TITLE }}
          body: ${{ env.RELEASE_BODY }}
          artifacts: result/merged.apk
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload patched APK release
        uses: ncipollo/release-action@v1
        with:
          tag: patched-${{ github.run_number }}
          name: Patched APK - ${{ env.RELEASE_TITLE }}
          body: ${{ env.RELEASE_BODY }}
          artifacts: ${{ env.PATCHED_APK }}
          token: ${{ secrets.GITHUB_TOKEN }}
