name: XAPK Patch Release

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-patch:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 安装 Java 22
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      # 3️⃣ 创建工作目录
      - name: Create folders
        run: |
          mkdir app
          mkdir result

      # 4️⃣ 下载 app.xapk（使用 wget + UA + referer）
      - name: Download app.xapk
        run: |
          echo "Downloading app.xapk from APKPure..."
          wget -O app.xapk \
            --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            --referer="https://apkpure.com" \
            "https://d.apkpure.com/b/XAPK/com.oddno.lovelive?version=latest"

      # 5️⃣ 下载最新 linkura-localify-arm64-v8a APK
      - name: Download latest linkura-localify arm64-v8a APK
        run: |
          echo "Fetching latest release from GitHub..."
          apiUrl="https://api.github.com/repos/ChocoLZS/linkura-localify/releases/latest"
          assetUrl=$(curl -s $apiUrl \
            | grep browser_download_url \
            | grep "linkura-localify-.*-debug-arm64-v8a\.apk" \
            | cut -d '"' -f 4)
          echo "Downloading $assetUrl ..."
          wget -O linkura-localify.apk "$assetUrl"

      # 6️⃣ 解压 XAPK
      - name: Expand XAPK
        run: unzip -o app.xapk -d app

      # 7️⃣ 使用 APKEditor 处理
      - name: Run APKEditor
        run: java -jar APKEditor.jar m -i app/

      # 8️⃣ 使用 LSPatch 打 patch
      - name: Run LSPatch
        run: |
          appMerged=$(ls app/*_merged.apk | head -n 1)
          echo "Found merged APK: $appMerged"
          patchApk=$(ls linkura-localify.apk | head -n 1)
          java -jar lspatch.jar "$appMerged" -m "$patchApk" -o result/

      # 9️⃣ 上传 result 到 Release
      - name: Upload result to release
        uses: ncipollo/release-action@v1
        with:
          tag: "patch-result-${{ github.run_number }}"
          name: "Patch Result ${{ github.run_number }}"
          files: result/*
          overwrite: true
