name: XAPK Patch Release

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-patch:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Python (for JSON parsing)
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Create folders
        run: |
          mkdir app
          mkdir result
        shell: powershell

      - name: Download app.xapk via Puppeteer
        run: node download_apkpure.js

      - name: Download latest linkura-localify arm64-v8a APK
        run: |
          echo "Fetching latest release from GitHub..."
          $apiUrl = "https://api.github.com/repos/ChocoLZS/linkura-localify/releases/latest"
          $release = Invoke-RestMethod -Uri $apiUrl
          $asset = $release.assets | Where-Object { $_.name -match "linkura-localify-.*-debug-arm64-v8a\.apk" } | Select-Object -First 1
          Write-Host "Downloading $($asset.name)..."
          Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $asset.name
        shell: powershell

      - name: Expand XAPK
        run: Expand-Archive -Path .\app.xapk -DestinationPath .\app -Force
        shell: powershell

      - name: Run APKEditor
        run: java -jar .\APKEditor.jar m -i .\app\
        shell: powershell

      - name: Run LSPatch
        run: |
          $appMerged = Get-ChildItem -Path .\app -Filter "*_merged.apk" | Select-Object -First 1
          Write-Host "Found merged APK: $($appMerged.FullName)"
          $patchApk = Get-ChildItem -Filter "linkura-localify-*-debug-arm64-v8a.apk" | Select-Object -First 1
          java -jar .\lspatch.jar $appMerged.FullName -m $patchApk.FullName -o .\result\
        shell: powershell

      - name: Upload result to release
        uses: ncipollo/release-action@v1
        with:
          tag: "patch-result-${{ github.run_number }}"
          name: "Patch Result ${{ github.run_number }}"
          files: result/*
          overwrite: true
