name: XAPK Patch Release

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-patch:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      # 4️⃣ Install Puppeteer
      - name: Install Puppeteer
        run: npm install puppeteer

      # 5️⃣ Create working folders
      - name: Create folders
        run: |
          mkdir -p app result

      # 6️⃣ Download app.xapk using Puppeteer
      - name: Download app.xapk
        run: node download_apkpure.js

      # 7️⃣ Download latest linkura-localify arm64-v8a APK
      - name: Download latest linkura-localify APK
        run: |
          echo "Fetching latest release from GitHub..."
          apiUrl="https://api.github.com/repos/ChocoLZS/linkura-localify/releases/latest"
          assetUrl=$(curl -s $apiUrl \
            | grep browser_download_url \
            | grep "linkura-localify-.*-debug-arm64-v8a\.apk" \
            | cut -d '"' -f 4)
          echo "Downloading $assetUrl ..."
          wget -O linkura-localify.apk "$assetUrl"

      # 8️⃣ Expand XAPK
      - name: Expand XAPK
        run: unzip -o app.xapk -d app

      # 9️⃣ Run APKEditor
      - name: Run APKEditor
        run: java -jar APKEditor.jar m -i app/

      # 🔟 Run LSPatch
      - name: Run LSPatch
        run: |
          appMerged=$(ls app/*_merged.apk | head -n 1)
          echo "Found merged APK: $appMerged"
          patchApk=$(ls linkura-localify.apk | head -n 1)
          java -jar lspatch.jar "$appMerged" -m "$patchApk" -o result/

      # 1️⃣1️⃣ Upload result to release
      - name: Upload result to release
        uses: ncipollo/release-action@v1
        with:
          tag: "patch-result-${{ github.run_number }}"
          name: "Patch Result ${{ github.run_number }}"
          files: result/*
          overwrite: true