name: XAPK Patch Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client jq unzip wget

      - name: Write SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Remote wget XAPK to server
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<'EOF'
            set -eux
            mkdir -p /opt/linkura-localify-auto-release-web/data
            cd /opt/linkura-localify-auto-release-web/data
            wget -O latest.apk \
              --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
              "https://d.apkpure.com/b/XAPK/com.oddno.lovelive?version=latest"
            ls -lh latest.apk
          EOF

      - name: Copy XAPK from server
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa -P ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/linkura-localify-auto-release-web/data/latest.apk \
            ./app.xapk
          ls -lh app.xapk

      - name: Download linkura-localify apk
        run: |
          url=$(curl -s https://api.github.com/repos/ChocoLZS/linkura-localify/releases/latest \
            | jq -r '.assets[] | select(.name | test("linkura-localify-.*-debug-arm64-v8a\\.apk")) | .browser_download_url' \
            | head -n1)
          wget -O linkura-localify.apk "$url"
          ls -lh linkura-localify.apk

      - name: Expand XAPK
        run: unzip -o app.xapk -d app

      - name: Run APKEditor
        run: java -jar APKEditor.jar m -i app/

      - name: Run LSPatch
        run: |
          apk=$(find app -name "*_merged.apk" | head -n1)
          java -jar lspatch.jar "$apk" -m linkura-localify.apk -o result
          ls -lh result

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: patch-${{ github.run_number }}
          name: Patch Result ${{ github.run_number }}
          files: result/*
          token: ${{ secrets.GITHUB_TOKEN }}
